// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelHealthGuide.Models.DatabaseModels;

namespace TravelHealthGuide.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20200513141509_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("TravelHealthGuide.Models.DatabaseModels.DestinationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiseaseRisks")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaccintionRequirements")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "AF",
                            CountryName = "Afghanistan",
                            DiseaseRisks = @"Malaria
Malaria risk due to P. falciparum and P. vivax exists from May through November below 2000 m.",
                            RecommendedActions = @"Malaria
Mosquito-bite prevention plus atovaquoneproguanil or doxycycline or mefloquine chemoprophylaxis.",
                            VaccintionRequirements = @"Polio
Proof of polio vaccination is required for travellers coming from a polio-endemic country. For residents or travellers who stay in Afghanistan for more than 4 weeks, a proof of polio vaccination may be required when departing from Afghanistan. This vaccination should be received between 4 weeks and 12 months before the date of departure."
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "AL",
                            CountryName = "Albania",
                            VaccintionRequirements = @"Yellow Fever
A yellow fever vaccination certificate is required for travellers aged 1 year or over arriving from countries with risk of yellow fever transmission."
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "ID",
                            CountryName = "Indonesia",
                            DiseaseRisks = @"Malaria
Malaria risk exists throughout the year in most areas of the five eastern provinces of East Nusa Tenggara, Maluku, North Maluku, Papua and West Papua. In other parts of the country, there is malaria risk in some districts, except in Jakarta municipality, in cities and urban areas, and in the areas of the main tourist resorts. P. vivax resistance to chloroquine has been reported. Human P. knowlesi infection has been reported in the province of Kalimantan.",
                            RecommendedActions = @"Malaria
Mosquito-bite prevention plus atovaquoneproguanil or doxycycline or mefloquine chemoprophylaxis.",
                            VaccintionRequirements = @"Yellow Fever
 a yellow fever vaccination certificate is required for travellers aged 9 months or over arriving from countries with risk of yellow fever transmission.||Meningitis
Proof of meningococcal (groups A, C, Y and W-135) meningitis vaccination is required for travellers departing to and arriving from Saudi Arabia"
                        });
                });

            modelBuilder.Entity("TravelHealthGuide.Models.DatabaseModels.UserInfo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
